### PR TITLE
Upgrade xm commons version from 2.0.6 to 2.1.0, upgrade lombok version

### PR DESCRIPTION
**Pull request by igordumchykov**
from 1.18.2 to 1.18.10, add mail sending support

### CODE REVIEW

**Comment by amedvedchuk** [comment]
@igordumchykov 
please check if this MR can be replaced with upcoming upgrade to java 11 & jhipster 6.5.x:
https://github.com/xm-online/tmf-ms-activation/pull/45

**Comment by igordumchykov** [comment]
@amedvedchuk

**Comment by igordumchykov** [comment]
@amedvedchuk xm commons and lombok upgrade can be replaced by #45 . But there is one more change: there were added mail provider, that we will need soon. Should I close this PR and create another one with mail provider support?

**Comment by amedvedchuk** [comment]
@igordumchykov 
i think you can even do not close this PR.
in case lombok upgrade is not critical for you then just revert lobmok version (it will be increased during upcoming java 11 upgrade). And we will merge this one to master. 
Then @vkirichenko please merge changes to java11 branch.

**Comment by igordumchykov** [comment]
Lombok version was reverted

**Pull request merged**
